{
 "title": "Logbook",
 "description": "Logs,Moorages,Stays",
 "time": { "from": "now-15d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "boat",
    "label": "Boat",
    "query": "SET \"user.email\" = '${__user.email}';\nSET vessel.id = '${__user.login}';\nSELECT\n        v.name AS __text,\n        m.vessel_id AS __value\n   FROM auth.vessels v\n   JOIN api.metadata m ON v.owner_email = '${__user.email}' and m.vessel_id = v.vessel_id;"
   }
  ]
 },
 "panels": [
  {
   "title": "Logbook ${__user.email} / ${__user.login}",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SET vessel.id = '${__user.login}';\nSELECT * from api.logs_view"
    }
   ]
  },
  {
   "title": "Stays",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SET vessel.id = '${__user.login}';\nSELECT * from api.stays_view"
    }
   ]
  },
  {
   "title": "Moorages",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "SET vessel.id = '${__user.login}';\nselect * from api.moorages_view"
    }
   ]
  }
 ]
}