{
 "title": "TimescaleDB Hypertables",
 "description": "Overview over TimescaleDB Hypertables and their space usage",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "database", "query": "postgres" }
  ]
 },
 "panels": [
  {
   "title": "Hypertables",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT count(1) FROM _timescaledb_catalog.hypertable"
    }
   ]
  },
  {
   "title": "Total Size",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 3, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT sum(total_bytes) FROM _timescaledb_catalog.hypertable, hypertable_detailed_size('api.metrics'::text);"
    }
   ]
  },
  {
   "title": "TimescaleDB",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 7, "y": 0 },
   "format": "none",
   "valueName": "last_time",
   "targets": [
    {
     "rawSql": "SELECT extversion FROM pg_extension WHERE extname='timescaledb'"
    }
   ]
  },
  {
   "title": "PostgreSQL",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 14, "x": 10, "y": 0 },
   "format": "bytes",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT current_setting('server_version');"
    }
   ]
  },
  {
   "title": "Table Size",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 2 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT sum(table_bytes) FROM _timescaledb_catalog.hypertable, hypertable_detailed_size('api.metrics'::text);"
    }
   ]
  },
  {
   "title": "Index Size",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 2 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT sum(index_bytes) FROM _timescaledb_catalog.hypertable, hypertable_detailed_size('api.metrics'::text);"
    }
   ]
  },
  {
   "title": "TOAST Size",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 2 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT sum(toast_bytes) FROM _timescaledb_catalog.hypertable, hypertable_detailed_size('api.metrics'::text);"
    }
   ]
  },
  {
   "title": "Chunksize",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "rawSql": "select table_name AS metric,to_timestamp(lower(ranges[1])/10^6) AS time ,total_bytes FROM _timescaledb_catalog.hypertable,chunks_detailed_size('api.metrics'::text) ORDER BY 1,2;\r\n"
    }
   ]
  },
  {
   "title": "Space Usage Hypertables",
   "type": "table-old",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT table_name AS \"Name\",table_bytes AS \"table\",index_bytes AS \"index\",toast_bytes AS \"toast\",total_bytes AS \"total\" FROM _timescaledb_catalog.hypertable, hypertable_detailed_size('api.metrics'::text) ORDER BY total_bytes DESC;"
    }
   ]
  },
  {
   "title": "Chunksize Stacked",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "rawSql": "select table_name AS metric,to_timestamp(lower(ranges[1])/10^6) AS time ,total_bytes FROM _timescaledb_catalog.hypertable,chunk_relation_size(table_name::text) ORDER BY 1,2;\r\n"
    }
   ]
  }
 ]
}