{
 "title": "Weather",
 "description": "Weather conditions",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "boat",
    "label": "Boat",
    "query": "SET \"user.email\" = '${__user.email}';\nSET vessel.client_id = '${__user.login}';\nSELECT\n        v.name AS __text,\n        m.client_id AS __value\n   FROM auth.vessels v\n   JOIN api.metadata m ON v.owner_email = '${__user.email}' and m.vessel_id = v.vessel_id;"
   }
  ]
 },
 "panels": [
  {
   "title": "Wind Speed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "velocityknot" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  cast(windspeedapparent AS numeric) * 1.9438444924406 AS windSpeed\nFROM api.metrics\nWHERE\n  $__timeFilter(time)\n  and client_id = '${boat}'\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Wind Angle",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT cast(anglespeedapparent AS numeric) AS windAngleTrue from api.metrics WHERE client_id = '${boat}' ORDER BY time DESC LIMIT 1;"
    }
   ]
  },
  {
   "title": "Outside Temp",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  cast(metrics-> 'environment.outside.temperature' AS numeric) - 273.15 AS outsideTemperature\nFROM api.metrics\nWHERE\n  $__timeFilter(time)\n  AND client_id = '${boat}'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Water Temp",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  cast(metrics-> 'environment.water.temperature' AS numeric) - 273.15 AS waterTemperature\nFROM api.metrics\nWHERE\n  $__timeFilter(time)\n  AND client_id = '${boat}'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Barometric Pressure",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SET vessel.client_id = '${__user.login}';\nSELECT\n  time AS \"time\",\n  cast(metrics-> 'environment.outside.pressure' AS numeric) * 0.00029530 AS outsidePressure\nFROM api.metrics\nWHERE\n  $__timeFilter(time)\n  AND client_id = '${boat}'\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Inside Temp",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SET vessel.client_id = '${__user.login}';\nSELECT\n  time AS \"time\",\n  cast(metrics-> 'environment.inside.temperature' AS numeric) - 273.15 AS insideTemperature\nFROM api.metrics\nWHERE\n  $__timeFilter(time)\n  AND client_id = '${boat}'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Inside Humidity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SET vessel.client_id = '${__user.login}';\nSELECT\n  time AS \"time\",\n  cast(metrics-> 'environment.outside.humidity' AS numeric) * 100 AS insideHumidity\nFROM api.metrics\nWHERE\n  $__timeFilter(time)\n  AND client_id = '${boat}'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Engine Room",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SET vessel.client_id = '${__user.login}';\nSELECT\n  time AS \"time\",\n  cast(metrics-> 'environment.engine.temperature' AS numeric) - 273.15 AS insideTemperature\nFROM api.metrics\nWHERE\n  $__timeFilter(time)\n  AND client_id = '${boat}'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Apparent Wind Speed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "velocityknot" } },
   "targets": [
    {
     "rawSql": "SET vessel.client_id = '${__user.login}';\nSELECT time AS \"time\", cast(windspeedapparent AS numeric) * 1.9438444924406 AS windSpeed\nFROM api.metrics\nWHERE\n  $__timeFilter(time)\n  AND client_id = '${boat}'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SET vessel.client_id = '${__user.login}';\nSELECT\n  time AS \"time\",\n  cast(metrics-> 'environment.water.temperature' AS numeric) - 273.15 AS waterTemperature,\n  cast(metrics-> 'environment.outside.temperature' AS numeric) - 273.15 AS outsideTemperature,\n  cast(metrics-> 'environment.inside.temperature' AS numeric) - 273.15 AS insideTemperature,\n  cast(metrics-> 'environment.inside.fridge.temperature' AS numeric) - 273.15 AS fridgeTemperature\nFROM api.metrics\nWHERE\n  $__timeFilter(time)\n  AND client_id = '${boat}'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Outside Temperature",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius", "label": "Temperature (C)" }
   ],
   "targets": [
    {
     "rawSql": "SET vessel.client_id = '${__user.login}';\nSELECT\n  time AS \"time\",\n  cast(metrics-> 'environment.outside.temperature' AS numeric) - 273.15 AS outsideTemperature\nFROM api.metrics\nWHERE\n  $__timeFilter(time)\n  AND client_id = '${boat}'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Barometric Pressure",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "yaxes": [
    { "format": "pressurehpa" }
   ],
   "targets": [
    {
     "rawSql": "SET vessel.client_id = '${__user.login}';\nSELECT\n  time AS \"time\",\n  cast(metrics-> 'environment.outside.pressure' AS numeric) * 0.00029530 AS outsideTemperature,\n  cast(metrics-> 'environment.inside.pressure' AS numeric) * 0.00029530 AS insideTemperature,\n  cast(metrics-> 'environment.inside.fridge.pressure' AS numeric) * 0.00029530 AS fridgeTemperature\nFROM api.metrics\nWHERE\n  $__timeFilter(time)\n  AND client_id = '${boat}'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Apparent Wind Angle",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SET vessel.client_id = '${__user.login}';\nSELECT\n  time AS \"time\",\n  anglespeedapparent\nFROM api.metrics\nWHERE\n  $__timeFilter(time)\n  AND client_id = '${boat}'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Apparent Wind Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "rawSql": "SET vessel.client_id = '${__user.login}';\nSELECT\n  time AS \"time\",\n  windSpeedApparent\nFROM api.metrics\nWHERE\n  $__timeFilter(time)\n  AND client_id = '${boat}'\nORDER BY 1"
    }
   ]
  }
 ]
}